>>> int('four')
>>> try:
...     int('four')
... except:
...     print('caught it')

>>> try:
...     int('four')
... except Exception as e:
...     print('caught:\n -> {0}\n -> {1}'
...         .format(e, repr(e))
...     save = e

>>> dir(save)
>>> save.args
